USE [master]
GO

DROP DATABASE J4_ToDoApp
GO

CREATE DATABASE J4_ToDoApp
GO

USE J4_ToDoApp
GO

CREATE TABLE ViecCanLam(
	MaCongViec BIGINT PRIMARY KEY IDENTITY(1,1),
	TenCongViec NVARCHAR(200) NOT NULL,
	NgayLam DATE NOT NULL,
	DaXong BIT NOT NULL,
	TienDo INT NOT NULL
)